---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: quay.io/ansible/creator-ee:latest
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
additional_build_steps:
  prepend:
    - RUN pip install --upgrade pip setuptools wheel
  append:
    - RUN dnf autoremove
